### ISSUE TITLE
Resource editor

### ISSUE THREAD

**Issue by GiselleSerate** [studycloud/studycloud#24]
Please plan and split into issues.

**Comment by GiselleSerate** [comment]
Can you recycle the modal view code from the register/forget component and/or add this as a component to the modal?

**Comment by GiselleSerate** [comment]
This issue is for me to style the resource editor. Backending has been delegated to the Javascript team (which can be split into its own issue if desired).

**Comment by LunaY0Yuki** [comment]
Completed by the time that issue #148 takes place. Issue #148 talks about improvements to the existing resource creator.
