### ISSUE TITLE
reinventing permissions

### ISSUE THREAD

**Issue by aryam7** [studycloud/studycloud#85]
Seems like our idea for a permission-role based system is not new. Why reinvent the wheel? Consider using [Entrust](https://github.com/Zizaco/entrust) to get the job done a lot more quickly.

**Comment by Maxwellfire** [comment]
That seems like a great idea!

**Comment by aryam7** [comment]
@claires99 
Here's a review that ranks a bunch of different permission-based systems that we can use with Laravel
https://laravel-news.com/two-best-roles-permissions-packages

**Comment by aryam7** [comment]
For next time: we want to call whereIs() multiple times to get all of the admins

**Comment by aryam7** [comment]
create migration, controller, model for Notices
also test the Factory

create pivot table for notice_users as well

**Comment by aryam7** [comment]
to debug the validation exception:
https://laravel.com/api/5.5/Illuminate/Validation/ValidationException.html
try the `errors()` method

**Comment by aryam7** [comment]
resolved in #85
